import Image from "next/image";
import { EXAMPLE_REFERENCES, EXAMPLE_DIRECTIONS } from "@/content/site";

/**
 * Real pipeline output, not mockups — the section claims as much, so the
 * screenshots in /public/examples must stay in sync with what the pipeline
 * actually produced for these three references.
 */
export default function RealOutput() {
  return (
    <section id="examples" className="bg-white">
      <div className="section text-center">
        <p className="eyebrow">Real Output</p>
        <h2 className="h2 mt-3">One project, three real directions.</h2>
        <p className="mx-auto mt-4 max-w-[52ch] text-sm text-muted">
          Generated by the actual VisiFrame pipeline for a real project brief.
        </p>

        <div className="mt-7 flex flex-wrap items-center justify-center gap-2">
          <span className="text-xs text-faint">Built from:</span>
          {EXAMPLE_REFERENCES.map((r) => (
            <code
              key={r}
              className="rounded-md border border-line bg-surface px-2.5 py-1 font-mono text-xs text-muted"
            >
              {r}
            </code>
          ))}
        </div>

        <ul className="mt-10 grid gap-5 md:grid-cols-3">
          {EXAMPLE_DIRECTIONS.map((d, i) => (
            <li
              key={d.name}
              className="overflow-hidden rounded-2xl border border-line bg-white text-left"
            >
              <div className="relative aspect-[16/10] bg-surface">
                <Image
                  src={`/examples/direction-${i + 1}.jpg`}
                  alt={`VisiFrame ${d.name}: ${d.caption}`}
                  fill
                  sizes="(max-width: 768px) 100vw, 33vw"
                  className="object-cover object-top"
                />
              </div>
              <div className="border-t border-line px-4 py-3">
                <p className="font-display text-sm font-bold">{d.name}</p>
                <p className="mt-0.5 text-xs text-muted">{d.caption}</p>
              </div>
            </li>
          ))}
        </ul>

        <p className="mt-8 text-sm text-muted">
          Same references. Same brand. Three genuinely different designs — not three
          tints of one.
        </p>
      </div>
    </section>
  );
}
