import Image from "next/image";
import { EXAMPLE_REFERENCES, EXAMPLE_DIRECTIONS } from "@/content/site";
import Reveal from "./Reveal";

/**
 * Real pipeline output, not mockups — the section says so, so the screenshots
 * in /public/examples must stay in sync with what was actually generated for
 * these three references.
 */
export default function RealOutput() {
  return (
    <Reveal id="examples" className="px-8 py-24">
      <div className="mx-auto max-w-[1180px]">
        <p className="m-0 mb-3 text-center text-[13px] font-bold uppercase tracking-[0.08em] text-accent-deep">
          Real Output
        </p>
        <h2 className="m-0 mb-3 text-center font-display text-[clamp(28px,3.4vw,38px)] font-bold">
          One project, three real directions.
        </h2>
        <p className="mx-auto mb-8 max-w-[560px] text-center text-base text-muted">
          Generated by the actual VisiFrame pipeline for a real project brief.
        </p>

        <div className="mb-10 flex flex-wrap items-center justify-center gap-2.5">
          <span className="text-[12.5px] text-note">Built from:</span>
          {EXAMPLE_REFERENCES.map((site) => (
            <span
              key={site}
              className="rounded-full border border-line bg-surface px-[13px] py-1.5 font-mono text-[12.5px] font-semibold"
            >
              {site}
            </span>
          ))}
        </div>

        <div className="grid grid-cols-[repeat(auto-fit,minmax(280px,1fr))] gap-6">
          {EXAMPLE_DIRECTIONS.map((v, i) => (
            <div
              key={v.name}
              className="overflow-hidden rounded-2xl border border-line bg-white"
            >
              <div className="relative aspect-[16/10] shrink-0 overflow-hidden bg-surface">
                <Image
                  src={`/examples/direction-${i + 1}.jpg`}
                  alt={`VisiFrame ${v.name}: ${v.caption}`}
                  fill
                  sizes="(max-width: 860px) 100vw, 33vw"
                  className="object-cover object-top"
                />
              </div>
              <div className="px-[18px] py-4">
                <p className="m-0 mb-1 text-[14.5px] font-bold text-ink">{v.name}</p>
                <p className="m-0 text-[13px] text-muted">{v.caption}</p>
              </div>
            </div>
          ))}
        </div>

        <p className="m-0 mt-8 text-center text-sm text-muted">
          Same references. Same brand. Three genuinely different designs — not three
          tints of one.
        </p>
      </div>
    </Reveal>
  );
}
